"""empty message

Revision ID: ad128ea3734d
Revises: 
Create Date: 2022-12-25 23:29:58.683364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad128ea3734d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'leaderboard', ['username'])
    op.create_unique_constraint(None, 'userdata', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userdata', type_='unique')
    op.drop_constraint(None, 'leaderboard', type_='unique')
    # ### end Alembic commands ###
